#!/usr/bin/env bash

test "$RACK_ENV"  || RACK_ENV="development"
test "$THIN_PORT" || THIN_PORT="4321"
test "$THIN_PID"  || THIN_PID="./log/listener.pid"
test "$THIN_LOG"  || THIN_LOG="./log/listener.log"

test -f ./config/thinrc && source ./config/thinrc

echo "RACK_ENV == $RACK_ENV"

test "$DEBUG"     && set -x

if ! test "$1"
then
	echo "usage: listener start|stop|restart"
	echo " "
	echo "takes the following configs as environemnt variables:"
	echo " "
	echo "  RACK_ENV  :: default $RACK_ENV"
	echo "  THIN_PORT :: default $THIN_PORT"
	echo "  THIN_PID  :: default $THIN_PID"
	echo "  THIN_LOG  :: default $THIN_LOG"
	echo " "
	exit 0
fi

# thin --port $THIN_PORT --pid $THIN_PID --environment $RACK_ENV --log $THIN_LOG --daemonize $1
RACK_ENV=$RACK_ENV bundle exec thin --port $THIN_PORT --pid $THIN_PID --log $THIN_LOG --daemonize $1
